# ros2_control Configuration for Delivery Robot
# 배달 로봇을 위한 ros2_control 설정

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # 컨트롤러 목록
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      
    gpio_controller:
      type: gpio_controllers/GpioController

# 차동 구동 컨트롤러
diff_drive_controller:
  ros__parameters:
    # 바퀴 설정
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    # 물리적 파라미터
    wheel_separation: 0.4         # 바퀴 간격 (m)
    wheel_radius: 0.1             # 바퀴 반지름 (m)
    
    # 속도 제한
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.8         # 최대 선속도 (m/s)
        min_velocity: -0.8        # 최소 선속도 (m/s)
        has_acceleration_limits: true
        max_acceleration: 1.0     # 최대 가속도 (m/s²)
        min_acceleration: -1.0    # 최소 가속도 (m/s²)
        has_jerk_limits: false
        max_jerk: 0.0
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0         # 최대 각속도 (rad/s)
        min_velocity: -2.0        # 최소 각속도 (rad/s)
        has_acceleration_limits: true
        max_acceleration: 1.5     # 최대 각가속도 (rad/s²)
        min_acceleration: -1.5    # 최소 각가속도 (rad/s²)
        has_jerk_limits: false
        max_jerk: 0.0
    
    # 토픽 및 프레임
    publish_rate: 50.0            # 발행 주파수 (Hz)
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # 기타 설정
    open_loop: false              # 오픈루프 제어 비활성화
    enable_odom_tf: true          # odom → base_link TF 발행

# 조인트 상태 브로드캐스터
joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    interfaces:
      - position
      - velocity

# GPIO 컨트롤러 (도어, LED 등)
gpio_controller:
  ros__parameters:
    # GPIO 핀 설정
    gpios:
      - name: "door_servo"
        pin: 18
        direction: "output"
        initial_value: 0
        
      - name: "status_led"
        pin: 24
        direction: "output" 
        initial_value: 0
        
      - name: "buzzer"
        pin: 25
        direction: "output"
        initial_value: 0
        
      - name: "emergency_button"
        pin: 22
        direction: "input"
        pull_resistor: "pull_up"
    
    # 업데이트 주기
    update_rate: 10.0             # Hz
    
# 모터 파라미터
motor_params:
  # 왼쪽 모터
  left_motor:
    encoder_resolution: 2048      # 엔코더 해상도 (펄스/회전)
    gear_ratio: 30.0              # 기어비
    max_rpm: 200                  # 최대 RPM
    
  # 오른쪽 모터
  right_motor:
    encoder_resolution: 2048      # 엔코더 해상도 (펄스/회전)
    gear_ratio: 30.0              # 기어비
    max_rpm: 200                  # 최대 RPM
    
  # PID 제어 파라미터
  pid_gains:
    kp: 0.5                       # 비례 게인
    ki: 0.1                       # 적분 게인
    kd: 0.05                      # 미분 게인
    windup_limit: 10.0            # 적분 와인드업 제한