# 지역 EKF 설정 (odom -> base_link 변환 생성)
# 연속적인 센서 데이터 (휠 오도메트리, IMU 각속도)를 융합하여 
# 부드럽지만 드리프트가 발생하는 로컬 위치 추정 제공

ekf_filter_node:
  ros__parameters:
    # 필터 주파수 (Hz) - 높은 주파수로 부드러운 추정
    frequency: 30.0
    
    # 2차원 평면 모드 (지상 로봇용)
    two_d_mode: true
    
    # 좌표계 정의
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # 변환 발행 설정
    publish_tf: true
    publish_acceleration: false
    
    # 센서 입력 설정
    
    # 오도메트리 (휠 엔코더)
    odom0: /odom
    odom0_config: [true,  true,  false,   # X, Y, Z 위치
                   false, false, false,   # Roll, Pitch, Yaw
                   true,  true,  false,   # X속도, Y속도, Z속도  
                   false, false, true,    # Roll각속도, Pitch각속도, Yaw각속도
                   false, false, false]   # X가속도, Y가속도, Z가속도
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_nodelay: true
    
    # IMU (자이로스코프)
    imu0: /imu/data
    imu0_config: [false, false, false,    # X, Y, Z 위치
                  false, false, true,     # Roll, Pitch, Yaw (방위각)
                  false, false, false,    # X속도, Y속도, Z속도
                  false, false, true,     # Roll각속도, Pitch각속도, Yaw각속도
                  true,  true,  false]    # X가속도, Y가속도, Z가속도
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_nodelay: true
    imu0_remove_gravitational_acceleration: true
    
    # 프로세스 노이즈 공분산 (Q 행렬)
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]
    
    # 초기 추정 공분산 (P 행렬)
    initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]