# navsat_transform_node 설정
# GPS 좌표를 ROS 좌표계로 변환하고 UTM -> MAP 변환 관리

navsat_transform:
  ros__parameters:
    # 노드 실행 주파수
    frequency: 30.0
    
    # 지연 시간 설정
    delay: 3.0
    
    # 자기 편각 보정 (한국 서울 기준 약 -7.5도 = -0.131 라디안)
    # NOAA 웹사이트에서 정확한 값 확인 권장: https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml
    magnetic_declination_radians: -0.131
    
    # IMU yaw 오프셋 (IMU가 동쪽을 0으로 하지 않고 북쪽을 0으로 할 경우)
    # ROS 표준 ENU: 동쪽 = 0도, IMU 표준: 북쪽 = 0도
    # 따라서 π/2 (90도) 오프셋 필요
    yaw_offset: 1.5708  # π/2 라디안
    
    # 고도 처리 (2D 평면 주행 시 true로 설정)
    zero_altitude: true
    
    # TF 변환 발행 설정
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame: false
    
    # datum 대기 설정 (정적 기준점 사용 시)
    wait_for_datum: false
    
    # 필터링된 GPS 좌표 발행 (디버깅용)
    publish_filtered_gps: true
    
    # 입력 토픽 설정
    # gps_topic: "/gps/fix"          # GPS 데이터 토픽
    # imu_topic: "/imu/data"         # IMU 데이터 토픽  
    # odometry_topic: "/odometry/local"  # 지역 오도메트리 토픽
    
    # 출력 토픽 설정
    # output_odometry_topic: "/odometry/gps"  # GPS 기반 오도메트리 출력
    
    # 좌표계 ID
    world_frame_id: "map"
    map_frame_id: "map" 
    odom_frame_id: "odom"
    base_link_frame_id: "base_link"
    utm_frame_id: "utm"
    
    # 변환 허용 오차
    transform_timeout: 0.0
    
    # 사용할 GPS 상태 (GPS fix 품질)
    # -1: 신호 없음, 0: 수신 불가, 1: GPS fix, 2: DGPS fix  
    use_odometry_yaw: false
    
    # NavSat 상태 임계값
    wait_for_datum_timeout: 0.0